version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/temp/data
      - ./scripts:/root/temp/scripts
      - /home/butterlyn/Documents:/root/documents/mount
    environment:
      - OPENAI_KEY
