version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/temp/data
      - ./scripts:/root/temp/scripts
      - ./documents:/root/documents
    environment:
      - OPENAI_KEY
