version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
    volumes:
      - ./data:/root/temp/data
      - ./scripts:/root/temp/scripts
      - ./documents:/root/documents
